- job:
    name: fuxi-dsvm-fullstack
    parent: legacy-dsvm-base
    run: playbooks/fuxi-dsvm-fullstack/run.yaml
    post-run: playbooks/fuxi-dsvm-fullstack/post.yaml
    timeout: 4200
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/devstack-plugin-container
      - openstack/fuxi

- job:
    name: fuxi-dsvm-py35-fullstack
    parent: legacy-dsvm-base
    run: playbooks/fuxi-dsvm-py35-fullstack/run.yaml
    post-run: playbooks/fuxi-dsvm-py35-fullstack/post.yaml
    timeout: 4200
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/devstack-plugin-container
      - openstack/fuxi

- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - fuxi-dsvm-fullstack
        - fuxi-dsvm-py35-fullstack
    gate:
      jobs:
        - fuxi-dsvm-fullstack
        - fuxi-dsvm-py35-fullstack
