- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - legacy-fuxi-dsvm-fullstack
        - legacy-fuxi-dsvm-py35-fullstack
    gate:
      jobs:
        - legacy-fuxi-dsvm-fullstack
        - legacy-fuxi-dsvm-py35-fullstack
